-- Таблица для хранения информации о просмотрах
CREATE TABLE IF NOT EXISTS hits (
                                    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                    app VARCHAR(255) NOT NULL,
    uri VARCHAR(1024) NOT NULL,
    ip VARCHAR(45) NOT NULL,
    timestamp TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
    );

-- Основные индексы
CREATE INDEX IF NOT EXISTS idx_hits_timestamp ON hits(timestamp DESC);
CREATE INDEX IF NOT EXISTS idx_hits_uri ON hits(uri);
CREATE INDEX IF NOT EXISTS idx_hits_app ON hits(app);
CREATE INDEX IF NOT EXISTS idx_hits_ip ON hits(ip);

-- Составные индексы для частых запросов
CREATE INDEX IF NOT EXISTS idx_hits_app_uri ON hits(app, uri);
CREATE INDEX IF NOT EXISTS idx_hits_timestamp_uri ON hits(timestamp, uri);
CREATE INDEX IF NOT EXISTS idx_hits_app_timestamp ON hits(app, timestamp);
CREATE INDEX IF NOT EXISTS idx_hits_uri_timestamp ON hits(uri, timestamp DESC);