-- stats/stats-server/src/main/resources/schema.sql

-- Таблица для хранения информации о просмотрах
CREATE TABLE IF NOT EXISTS hits (
                                    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                    app VARCHAR(255) NOT NULL CHECK (LENGTH(TRIM(app)) >= 1),
    uri VARCHAR(1024) NOT NULL CHECK (LENGTH(TRIM(uri)) >= 1),
    ip VARCHAR(45) NOT NULL CHECK (ip ~ '^([0-9]{1,3}\.){3}[0-9]{1,3}$|^([0-9a-fA-F]{1,4}:){7}[0-9a-fA-F]{1,4}$'),
    timestamp TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT chk_timestamp_range CHECK (timestamp >= '2020-01-01' AND timestamp <= CURRENT_TIMESTAMP + INTERVAL '1 year'),
    CONSTRAINT uq_hit_unique UNIQUE (app, uri, ip, timestamp)
    );

-- Основные индексы
CREATE INDEX IF NOT EXISTS idx_hits_timestamp ON hits(timestamp DESC);
CREATE INDEX IF NOT EXISTS idx_hits_uri ON hits(uri);
CREATE INDEX IF NOT EXISTS idx_hits_app ON hits(app);
CREATE INDEX IF NOT EXISTS idx_hits_ip ON hits(ip);

-- Составные индексы для частых запросов
CREATE INDEX IF NOT EXISTS idx_hits_app_uri ON hits(app, uri);
CREATE INDEX IF NOT EXISTS idx_hits_timestamp_uri ON hits(timestamp, uri);
CREATE INDEX IF NOT EXISTS idx_hits_app_timestamp ON hits(app, timestamp);
CREATE INDEX IF NOT EXISTS idx_hits_uri_timestamp ON hits(uri, timestamp DESC);

-- Индекс для уникальных подсчетов
CREATE INDEX IF NOT EXISTS idx_hits_app_uri_ip ON hits(app, uri, ip);