-- core/main-service/src/main/resources/schema.sql

-- Таблица пользователей
CREATE TABLE IF NOT EXISTS users (
                                     id    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                     name  VARCHAR(255)        NOT NULL CHECK (LENGTH(TRIM(name)) >= 2),
    email VARCHAR(512) UNIQUE NOT NULL CHECK (LENGTH(TRIM(email)) >= 6)
    );

-- Индексы для пользователей
CREATE UNIQUE INDEX IF NOT EXISTS idx_users_email_lower ON users (LOWER(email));
CREATE INDEX IF NOT EXISTS idx_users_name ON users (name);

-- Таблица категорий
CREATE TABLE IF NOT EXISTS categories (
                                          id   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                          name VARCHAR(50) UNIQUE NOT NULL CHECK (LENGTH(TRIM(name)) >= 1)
    );

-- Индексы для категорий
CREATE UNIQUE INDEX IF NOT EXISTS idx_categories_name_lower ON categories (LOWER(name));

-- Таблица событий
CREATE TABLE IF NOT EXISTS events (
                                      id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                      title VARCHAR(120) NOT NULL CHECK (LENGTH(TRIM(title)) >= 3),
    annotation VARCHAR(2000) NOT NULL CHECK (LENGTH(TRIM(annotation)) >= 20),
    description TEXT CHECK (LENGTH(TRIM(description)) >= 20 OR description IS NULL),
    category_id BIGINT NOT NULL,
    initiator_id BIGINT NOT NULL,
    event_date TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    created_at TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    published_on TIMESTAMP WITHOUT TIME ZONE,
    location_lat DOUBLE PRECISION NOT NULL CHECK (location_lat BETWEEN -90 AND 90),
    location_lon DOUBLE PRECISION NOT NULL CHECK (location_lon BETWEEN -180 AND 180),
    paid BOOLEAN NOT NULL DEFAULT FALSE,
    participant_limit INT NOT NULL DEFAULT 0 CHECK (participant_limit >= 0),
    request_moderation BOOLEAN NOT NULL DEFAULT TRUE,
    state VARCHAR(20) NOT NULL CHECK (state IN ('PENDING', 'PUBLISHED', 'CANCELED')),

    -- Ограничения внешних ключей
    CONSTRAINT fk_events_category FOREIGN KEY (category_id)
    REFERENCES categories (id) ON DELETE RESTRICT,
    CONSTRAINT fk_events_initiator FOREIGN KEY (initiator_id)
    REFERENCES users (id) ON DELETE CASCADE,

    -- Проверка дат
    CONSTRAINT chk_event_date_future CHECK (event_date > created_at),
    CONSTRAINT chk_published_date CHECK (
(state = 'PUBLISHED' AND published_on IS NOT NULL) OR
(state != 'PUBLISHED' AND published_on IS NULL)
    )
    );

-- Индексы для событий
CREATE INDEX IF NOT EXISTS idx_events_category_id ON events(category_id);
CREATE INDEX IF NOT EXISTS idx_events_initiator_id ON events(initiator_id);
CREATE INDEX IF NOT EXISTS idx_events_state ON events(state);
CREATE INDEX IF NOT EXISTS idx_events_event_date ON events(event_date DESC);
CREATE INDEX IF NOT EXISTS idx_events_created_at ON events(created_at DESC);
CREATE INDEX IF NOT EXISTS idx_events_location ON events(location_lat, location_lon);
CREATE INDEX IF NOT EXISTS idx_events_state_date ON events(state, event_date);

-- Частичные индексы для оптимизации
CREATE INDEX IF NOT EXISTS idx_events_published ON events(event_date)
    WHERE state = 'PUBLISHED';

-- Таблица запросов на участие
CREATE TABLE IF NOT EXISTS participation_requests (
                                                      id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                                      requester_id BIGINT NOT NULL,
                                                      event_id BIGINT NOT NULL,
                                                      created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
                                                      status VARCHAR(20) NOT NULL CHECK (status IN ('PENDING', 'CONFIRMED', 'REJECTED', 'CANCELED')),

    -- Ограничения внешних ключей
    CONSTRAINT fk_requests_requester FOREIGN KEY (requester_id)
    REFERENCES users (id) ON DELETE CASCADE,
    CONSTRAINT fk_requests_event FOREIGN KEY (event_id)
    REFERENCES events (id) ON DELETE CASCADE,

    -- Уникальность запроса
    CONSTRAINT uq_requester_event UNIQUE (requester_id, event_id),

    -- Проверка даты создания
    CONSTRAINT chk_request_date CHECK (created_at <= CURRENT_TIMESTAMP)
    );

-- Индексы для запросов на участие
CREATE INDEX IF NOT EXISTS idx_requests_requester_id ON participation_requests(requester_id);
CREATE INDEX IF NOT EXISTS idx_requests_event_id ON participation_requests(event_id);
CREATE INDEX IF NOT EXISTS idx_requests_status ON participation_requests(status);
CREATE INDEX IF NOT EXISTS idx_requests_created_at ON participation_requests(created_at DESC);
CREATE INDEX IF NOT EXISTS idx_requests_event_status ON participation_requests(event_id, status);

-- Таблица подборок
CREATE TABLE IF NOT EXISTS compilations (
                                            id     BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                            title  VARCHAR(255) NOT NULL CHECK (LENGTH(TRIM(title)) >= 1),
    pinned BOOLEAN NOT NULL DEFAULT FALSE,

    CONSTRAINT uq_compilation_title UNIQUE (title)
    );

-- Индексы для подборок
CREATE INDEX IF NOT EXISTS idx_compilations_pinned ON compilations(pinned);

-- Связующая таблица для связи "подборка-события" (many-to-many)
CREATE TABLE IF NOT EXISTS compilation_events (
                                                  compilation_id BIGINT NOT NULL,
                                                  event_id       BIGINT NOT NULL,
                                                  added_at       TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP,

                                                  CONSTRAINT pk_compilation_events PRIMARY KEY (compilation_id, event_id),
    CONSTRAINT fk_compilation_events_compilation FOREIGN KEY (compilation_id)
    REFERENCES compilations (id) ON DELETE CASCADE,
    CONSTRAINT fk_compilation_events_event FOREIGN KEY (event_id)
    REFERENCES events (id) ON DELETE CASCADE
    );

-- Индексы для связующей таблицы
CREATE INDEX IF NOT EXISTS idx_compilation_events_event ON compilation_events(event_id);
CREATE INDEX IF NOT EXISTS idx_compilation_events_compilation ON compilation_events(compilation_id);

-- Таблица комментариев
CREATE TABLE IF NOT EXISTS comments (
                                        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                        event_id BIGINT NOT NULL,
                                        user_id BIGINT NOT NULL,
                                        text TEXT NOT NULL CHECK (LENGTH(TRIM(text)) BETWEEN 1 AND 2000),
    created_at TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    status VARCHAR(20) NOT NULL DEFAULT 'PUBLISHED'
    CHECK (status IN ('PUBLISHED', 'EDITED', 'DELETED')),

    -- Ограничения внешних ключей
    CONSTRAINT fk_comments_event FOREIGN KEY (event_id)
    REFERENCES events (id) ON DELETE CASCADE,
    CONSTRAINT fk_comments_user FOREIGN KEY (user_id)
    REFERENCES users (id) ON DELETE CASCADE,

    -- Проверка дат
    CONSTRAINT chk_comment_dates CHECK (updated_at >= created_at)
    );

-- Индексы для комментариев
CREATE INDEX IF NOT EXISTS idx_comments_event_id ON comments(event_id);
CREATE INDEX IF NOT EXISTS idx_comments_user_id ON comments(user_id);
CREATE INDEX IF NOT EXISTS idx_comments_status ON comments(status);
CREATE INDEX IF NOT EXISTS idx_comments_created_at ON comments(created_at DESC);
CREATE INDEX IF NOT EXISTS idx_comments_event_created ON comments(event_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_comments_user_created ON comments(user_id, created_at DESC);

-- Сложный индекс для поиска активных комментариев
CREATE INDEX IF NOT EXISTS idx_comments_active ON comments(event_id, created_at DESC)
    WHERE status IN ('PUBLISHED', 'EDITED');

-- Вью для статистики по событиям
CREATE OR REPLACE VIEW event_stats AS
SELECT
    e.id as event_id,
    e.title,
    e.state,
    e.event_date,
    COUNT(DISTINCT pr.id) as confirmed_requests,
    COUNT(DISTINCT c.id) as comment_count
FROM events e
         LEFT JOIN participation_requests pr ON e.id = pr.event_id AND pr.status = 'CONFIRMED'
         LEFT JOIN comments c ON e.id = c.event_id AND c.status IN ('PUBLISHED', 'EDITED')
GROUP BY e.id;

-- Функция для проверки доступности события
CREATE OR REPLACE FUNCTION is_event_available(event_id_param BIGINT)
RETURNS BOOLEAN AS $$
DECLARE
participant_limit_val INT;
    confirmed_count INT;
BEGIN
SELECT participant_limit INTO participant_limit_val
FROM events WHERE id = event_id_param;

SELECT COUNT(*) INTO confirmed_count
FROM participation_requests
WHERE event_id = event_id_param AND status = 'CONFIRMED';

RETURN participant_limit_val = 0 OR confirmed_count < participant_limit_val;
END;
$$ LANGUAGE plpgsql;